"""
Worker script for AFToolkit extraction.
Run this ONLY with the Python interpreter from the AFToolkit environment.

Input: manifest CSV generated by make_embeddings_aft.py
Output: one md5(sequence).pt file per sequence, containing an [L, D] float tensor.
"""

from __future__ import annotations

import argparse
import csv
import os
from pathlib import Path
from typing import Sequence

import numpy as np
from tqdm.auto import tqdm

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True

torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False


# Must be available in the dedicated AFToolkit env.
from AFToolkit.processing.protein_task import ProteinTask
from AFToolkit.processing.openfold_wrapper import OpenFoldWrapper


def extract_lxd_tensor(protein_task: ProteinTask, feature_names: Sequence[str]) -> torch.Tensor:
    sorted_positions, array_feats = protein_task.get_array_protein_of_features(
        list(feature_names),
        protein_task.get_wildtype_protein_of_features(),
        protein_task.get_wildtype_observable_positions(),
    )
    arr = np.asarray(array_feats, dtype=np.float32)
    if arr.ndim != 2:
        raise RuntimeError(f"Expected 2D residue feature array [L, D], got shape={arr.shape}")
    return torch.from_numpy(arr)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest_csv", type=Path)
    parser.add_argument("--features", nargs="+", default=["single", "pair", "lddt_logits", "plddt"])
    parser.add_argument("--recycles", type=int, default=4)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--always-use-template", action="store_true")
    parser.add_argument("--side-chain-mask", action="store_true")
    parser.add_argument("--return-all-cycles", action="store_true")
    args = parser.parse_args()

    with args.manifest_csv.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        print("Manifest is empty. Nothing to do.")
        return

    out_dir = Path(rows[0]["out_path"]).resolve().parent
    status_path = out_dir / "aft_status.csv"

    of_wrapper = OpenFoldWrapper(
        device=args.device,
        inference_n_recycle=args.recycles,
        always_use_template=args.always_use_template,
        side_chain_mask=args.side_chain_mask,
        return_all_cycles=args.return_all_cycles,
    )
    of_wrapper.init_model()

    with status_path.open("w", encoding="utf-8", newline="") as sf:
        status_writer = csv.DictWriter(
            sf,
            fieldnames=["label", "accession", "seq_hash", "status", "detail", "length", "feature_dim"],
        )
        status_writer.writeheader()

        pbar = tqdm(rows, desc="AFToolkit embeddings", dynamic_ncols=True)
        for row in pbar:
            label = row["label"]
            accession = row["accession"]
            seq_hash = row["seq_hash"]
            seq = row["sequence"]
            pdb_path = row["pdb_path"]
            out_path = Path(row["out_path"])
            chain = row.get("chain", "A") or "A"

            if out_path.exists():
                status_writer.writerow(
                    {
                        "label": label,
                        "accession": accession,
                        "seq_hash": seq_hash,
                        "status": "cached",
                        "detail": str(out_path),
                        "length": "",
                        "feature_dim": "",
                    }
                )
                continue

            try:
                task = ProteinTask()
                task.set_input_protein_task(protein_path=str(pdb_path), chains=[chain])
                task.set_task_mutants({})
                with torch.inference_mode():
                    task.evaluate(of_wrapper=of_wrapper, store_of_protein=False)

                x = extract_lxd_tensor(task, args.features)
                if x.shape[0] != len(seq):
                    raise RuntimeError(
                        f"length mismatch: embedding L={x.shape[0]} vs sequence L={len(seq)} "
                        f"for accession={accession}, chain={chain}, pdb={pdb_path}"
                    )

                out_path.parent.mkdir(parents=True, exist_ok=True)
                torch.save(x.float().cpu(), out_path)
                status_writer.writerow(
                    {
                        "label": label,
                        "accession": accession,
                        "seq_hash": seq_hash,
                        "status": "ok",
                        "detail": str(out_path),
                        "length": int(x.shape[0]),
                        "feature_dim": int(x.shape[1]),
                    }
                )
                pbar.set_postfix(ok=1, L=int(x.shape[0]), D=int(x.shape[1]))
            except Exception as e:
                status_writer.writerow(
                    {
                        "label": label,
                        "accession": accession,
                        "seq_hash": seq_hash,
                        "status": "error",
                        "detail": repr(e),
                        "length": "",
                        "feature_dim": "",
                    }
                )

    print(f"Worker status saved to: {status_path}")


if __name__ == "__main__":
    main()
